[features]
seeds = true
skip-lint = false
[programs.localnet]
de_community = "AHJ8w9ePSzS7mjhXV4LAqatQtdEk9DpTgTLdzrpHU6P2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
